name: Release

on:
  push:
    branches:
      - versioning

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set Git user
        run: |
          git config --global user.email "francis.owusu@amalitech.com"
          git config --global user.name "francis-buabin-owusu"

      - name: Install dependencies
        run: npm install

      - name: Release
        env:
          RELEASE_VERSION: ${{ github.ref }}
          RELEASE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
